### PR TITLE
HotFix: linking place of birth with country list

### PR DESCRIPTION
**Pull request by Amna-Alshawa**

### CODE REVIEW

**Comment by pjamsheer** [comment]
@Amna-onefm Please fix Employee json conflict and we dont need custom permission in employee json

**Comment by Amna-Alshawa** [comment]
@pjamsheer , sure

**Comment by pjamsheer** [comment]
@Amna-onefm in employee.json fcm_token field is removed in your commit

**Comment by pjamsheer** [comment]
@Amna-onefm  you removed status value Vacation in employee.json

**Comment by Amna-Alshawa** [comment]
@pjamsheer , the Status field is not removed. It is only shifted under the token field.

**Comment by pjamsheer** [comment]
@Amna-onefm Status field is there but one of the option Vacation is missing

**Comment by Amna-Alshawa** [comment]
@pjamsheer , thank you for updating me.

**Review by pjamsheer — APPROVED** [review]

**Pull request merged**
