### PR TITLE
[Chore] add child table to enable employees to fill in one or more health insurance providers

### PR DESCRIPTION
**Pull request by NoBoneZ**
## Is this a Feature, Chore or Bug?
- [] Feature
- [x] Chore
- [] Bug

## Clearly and concisely describe the feature, chore or bug.
A child table was added to the health insurance section, so that an employee can fill in as many helath insurance as he has, duplicates are not allowed

## Analysis and design (optional)
Analyse and attach the design documentation

## Solution description
Describe your code changes in detail for reviewers.

## Is there a business logic within a doctype?
    - [] Yes
    - [] No

## Output screenshots (optional)
Post the output screenshots, if a UI is affected or added due to this feature.

## Areas affected and ensured
List out the areas affected by your code changes.
Health insurance section of the Employee Doctype 

## Is there any existing behavior change of other features due to this code change?
Mention Yes or No. If Yes, provide the appropriate explanation.

## Did you test with the following dataset?
- [] Existing Data
- [x] New Data

## Was child table created?
    - [] is attachment required?
        did you test attachment
## Did you delete custom field?
    - [] Yes
    - [x] No
        If yes, did you write a delete patch?

## Is patch required?
- [] Yes
- [x] No
    ## Was the patch test?

## Which browser(s) did you use for testing?
  - [x] Chrome
  - [] Safari
  - [] Firefox
Screenshot from 2022-12-28 17-58-59

### CODE REVIEW

**Comment by pjamsheer** [comment]
@NoBoneZ Update Areas affected and ensured in the PR Comment

**Comment by NoBoneZ** [comment]
> @NoBoneZ Update Areas affected and ensured in the PR Comment

I have done that ...

**Comment by mymi14s** [comment]
@NoBoneZ custom doctype will not be accepted, ensure the health provider is in one fm app, choose the correct module, I think GRD.

aswell ass name the doctype like Health Insurance Provider Detail.

It helps to quickly identify child doctype (adding detail or items to name)

**Comment by NoBoneZ** [comment]
> @NoBoneZ custom doctype will not be accepted, ensure the health provider is in one fm app, choose the correct module, I think GRD.
> 
> aswell ass name the doctype like Health Insurance Provider Detail.
> 
> It helps to quickly identify child doctype (adding detail or items to name)

@mymi14s , i have made the changes

**Review by mymi14s — APPROVED** [review]

**Pull request merged**
