### PR TITLE
[FEAT] modify API for Checkin

### PR DESCRIPTION
**Pull request by NoBoneZ**
## Is this a Feature, Chore or Bug?
- [x] Feature
- [] Chore
- [] Bug

## Clearly and concisely describe the feature, chore or bug.
Add response based on certain conditions

## Analysis and design (optional)
Analyse and attach the design documentation

## Solution description
Describe your code changes in detail for reviewers.
added checkers to the verify_checkin_checkout endpoint

## Is there a business logic within a doctype?
    - [] Yes
    - [] No

## Output screenshots (optional)
Post the output screenshots, if a UI is affected or added due to this feature.

## Areas affected and ensured
List out the areas affected by your code changes.
Checkin API

## Is there any existing behavior change of other features due to this code change?
Mention Yes or No. If Yes, provide the appropriate explanation.

## Did you test with the following dataset?
- [x] Existing Data
- [] New Data

## Was child table created?
    - [] is attachment required?
        did you test attachment
## Did you delete custom field?
    - [] Yes
    - [x] No
        If yes, did you write a delete patch?

## Is patch required?
- [] Yes
- [x] No
    ## Was the patch test?

## Which browser(s) did you use for testing?
  - [] Chrome
  - [] Safari
  - [] Firefox

### CODE REVIEW

**Review by mymi14s — APPROVED** [review]
@NoBoneZ there is so much introduction in here, I hope you test this with your mobile app.

**Comment by mymi14s** [comment]
@NoBoneZ please resolve the conflict above.

**Comment by mymi14s** [comment]
@NoBoneZ compare with staging branch before fixing the issue.

**Comment by mymi14s** [comment]
@NoBoneZ is this okay now?

**Comment by NoBoneZ** [comment]
> @NoBoneZ is this okay now?

@mymi14s , yes it is

**Comment by mymi14s** [comment]
@NoBoneZ there is a conflict, please fix it

**Comment by NoBoneZ** [comment]
> @NoBoneZ there is a conflict, please fix it

@mymi14s , Done, Sir 

> @NoBoneZ there is a conflict, please fix it

@mymi14s , Done, Sir

**Review by mymi14s — APPROVED** [review]

**Pull request merged**
