### PR TITLE
Changes:return site and location in same function

### PR DESCRIPTION
**Pull request by SalShai**

### CODE REVIEW

**Comment by pjamsheer** [comment]
@SalShai 
if there is nothing in location, what will be location[0] ?

**Comment by SalShai** [comment]
If these is nothing is location, it'll return None.

**Comment by SalShai** [comment]
@pjamsheer I'm sorry, I didn't think of that condition. I have made the required changes. Kindly, Check.

**Comment by pjamsheer** [comment]
@SalShai Please do if check before you assigning location[0] to some field, since if location is not there it will through list index out of range

**Review by pjamsheer — APPROVED** [review]

**Pull request merged**
