### PR TITLE
Feat: Use migrated services for facial recognition

### PR DESCRIPTION
**Pull request by Ehtesham599**
## Feature description
This PR enables using the externally hosted microservices for facial recognition during checkin/checkout and enrollment.

## Solution description
- Refactored current implementation to use hosted microservices for face verification and enrollment during checkin/checkout and accept penalty.
- Implemented gRPC client stubs for communication with microservices.
- User encodings (created when enrolling ) will no longer be stored this instance, rather on GCS.

## Areas affected and ensured
Checkin/checkout. Thoroughly tested and ensured.

## Is there any existing behavior change of other features due to this code change?
No.

## Was this feature tested on all the browsers?
  - [x] Chrome
  - [x] Safari

### CODE REVIEW

**Comment by Ehtesham599** [comment]
A merge was made to thoroughly test newly added changes which is why there are many file changes in this PR.

**Comment by mymi14s** [comment]
@Ehtesham599 did you actually work on 25 files or there is something wrong?

**Comment by mymi14s** [comment]
What possible impact could this PR have on current system functionalities.

**Comment by Ehtesham599** [comment]
> @Ehtesham599 did you actually work on 25 files or there is something wrong?

As you can see in the above comment, this branch had been created a while back and since then, staging has had new changes and in order to test this feature with the new changes, it changes on staging were merged with this branch. 
In the commit history on this PR, you can see contributions made by other team members.

**Comment by Ehtesham599** [comment]
> What possible impact could this PR have on current system functionalities.

Please read the PR description for the impact it can have on the current system functionalities.

**Review by mymi14s — APPROVED** [review]

**Pull request merged**
