### PR TITLE
WIP: Apply for leave and early arrive api

### PR DESCRIPTION
**Pull request by Amna-Alshawa**
- API: Applying for shift permission.
- API: return roles upon employee id.
- Customizing shift permission.

### CODE REVIEW

**Comment by Amna-Alshawa** [comment]
@pjamsheer , Kindly, review my PR.

**Comment by pjamsheer** [comment]
@Amna-onefm 
- [x]  Typo in the comment one_fm/api/mobile/shift_permission.py
- [x] leave a space in between the # and the comment that is the standard !
- [x] leave a space after comma
- [x] function set_shift_details is fetching the details, I suggest you for a function name change like get_shift_details

**Comment by Amna-Alshawa** [comment]
@pjamsheer , Kindly, review the API after adding the suggested modification to the code.

**Comment by pjamsheer** [comment]
@Amna-onefm 
- [x] one_fm/api/mobile/authentication.py remove unwanted comments or commented code
- [x] one_fm/api/mobile/shift_permission.py remove whitespace from L#55 to L#67

**Comment by Amna-Alshawa** [comment]
@pjamsheer , Thank you for your update will modify it rn.

**Comment by Amna-Alshawa** [comment]
@pjamsheer , Kindly review the code.

**Comment by pjamsheer** [comment]
@Amna-onefm 

- [x] What is the use of Procfile

**Comment by Amna-Alshawa** [comment]
@pjamsheer , removed Procfile file.

**Review by pjamsheer — APPROVED** [review]

**Pull request merged**
