### PR TITLE
chore: Reinstate Shift Validation"

### PR DESCRIPTION
**Pull request by mymi14s**
## Is this a Feature, Chore or Bug?
- [] Feature
- [x] Chore
- [] Bug

## Clearly and concisely describe the feature, chore or bug.
This PR reinstate shift validation that check if shifts were created then sends out notification if non.

## Analysis and design (optional)
Analyse and attach the design documentation

## Solution description
Describe your code changes in detail for reviewers.

## Is there a business logic within a doctype?
    - [] Yes
    - [] No

## Output screenshots (optional)
Post the output screenshots, if a UI is affected or added due to this feature.

## Areas affected and ensured
List out the areas affected by your code changes.

## Is there any existing behavior change of other features due to this code change?
Mention Yes or No. If Yes, provide the appropriate explanation.

## Did you test with the following dataset?
- [] Existing Data
- [] New Data

## Was child table created?
    - [] is attachment required?
        did you test attachment
## Did you delete custom field?
    - [] Yes
    - [] No
        If yes, did you write a delete patch?

## Is patch required?
- [] Yes
- [] No
    ## Was the patch test?

## Which browser(s) did you use for testing?
  - [] Chrome
  - [] Safari
  - [] Firefox

### CODE REVIEW

**Comment by mymi14s** [comment]
@SalShai please review this PR

**Comment by mymi14s** [comment]
@SalShai this is yet to be reviewed

**Review by SalShai — APPROVED** [review]

**Comment by SalShai** [comment]
@mymi14s Kindly base it staging??

**Comment by mymi14s** [comment]
@SalShai it's hotfix

**Comment by mymi14s** [comment]
Needed Asap

**Comment by SalShai** [comment]
@mymi14s Noted. It's approved. Kindly merge.

**Pull request merged**
