### PR TITLE
Site Allowance and other Fixes

### PR DESCRIPTION
**Pull request by SalShai**

### CODE REVIEW

**Comment by pjamsheer** [comment]
@SalShai Operations Site is a doctype in ONEFM App. What is the purpose of adding custom filed to it !!

**Comment by SalShai** [comment]
@pjamsheer , this is to include site allowance if any. This allowance will then be calculated according to attendance, and get added as additional salary component in Salary Slip.

**Comment by pjamsheer** [comment]
@SalShai Please add all the fields through the doctype itself (except workflow related fields), since it is doctype (Operations Site) belongs to one fm app.

**Comment by SalShai** [comment]
@pjamsheer , Thank you for pointing that out. I have made the requested changes. Kindly, have a look.

**Review by pjamsheer — APPROVED** [review]

**Pull request merged**
