### PR TITLE
#179977491: Fix: Notification in IOS

### PR DESCRIPTION
**Pull request by SalShai**

### CODE REVIEW

**Review by Ehtesham599 — CHANGES_REQUESTED** [review]
Add `category` field under APS for IOS.

**Comment by SalShai** [comment]
@Ehtesham599 , I made the changes. But, Also added the rest API code just in case we need it in the future.

**Review by Ehtesham599 — CHANGES_REQUESTED** [review]
- [ ] Please provide documentation for the new function.
- [ ] Follow appropriate naming for the function.
- [ ] Make sure to queue the execution of this function to the background as waiting for a response results in blocking code.

**Comment by SalShai** [comment]
@Ehtesham599 , kinda created a bigger mess.

**Comment by SalShai** [comment]
Closing due to conflicts.

**Pull request closed without merging**
