### PR TITLE
#181649822

### PR DESCRIPTION
**Pull request by SalShai**
## Feature description
- Send an Email to the Issuer when the issue has been closed.

## Solution description
- On update, if the status of the issue is closed, send an email to the issuer.

## Output screenshots (optional)
Screen Shot 2022-03-24 at 4 40 31 PM

## Areas affected and ensured
- check if contact of the issuer exists. 
- check if the status is close.
- send an email if the status is close.

## Is there any existing behavior change of other features due to this code change?
Yes, An email is sent when the issue has been closed.

## Was this feature tested on all the browsers?
  - [x] Chrome
  - [x] Safari

### CODE REVIEW

**Comment by mymi14s** [comment]
@Ehtesham599 can you check the Issue hooks with yours?

**Comment by Ehtesham599** [comment]
@mymi14s This PR is adding an `on_update` hook. Looks good to me.
@SalShai Resolve conflicts.

**Comment by SalShai** [comment]
@Ehtesham599 , Conflict Resolved. Could you review?

**Review by Ehtesham599 — APPROVED** [review]
Looks good to me

**Pull request merged**
