### PR TITLE
fix: Item Reservation and Stock balance (reservation) and RFM (added create IR)

### PR DESCRIPTION
**Pull request by mymi14s**
fix: Item Reservation and Stock balance (reservation) and RFM (added create IR):
Item Reservation can now be created from Request for Material Item (child) table.

image

### CODE REVIEW

**Comment by pjamsheer** [comment]
@mymi14s There is a conflict with the modified field. Resolve it and push again

**Comment by mymi14s** [comment]
> @mymi14s There is a conflict with the modified field. Resolve it and push again

I have made changes

**Comment by pjamsheer** [comment]
@mymi14s Your Last commit having Quotation Comparison Sheet commits too. Please remove those commits and push again

**Comment by mymi14s** [comment]
> @mymi14s Your Last commit having Quotation Comparison Sheet commits too. Please remove those commits and push again

@pjamsheer changes has been effected and json file fixed

**Review by pjamsheer — APPROVED** [review]

**Pull request merged**
