### PR TITLE
Push Notification 

### PR DESCRIPTION
**Pull request by SalShai**

### CODE REVIEW

**Comment by pjamsheer** [comment]
@SalShai There are lots of print, in server we dont need any print.

**Comment by SalShai** [comment]
@pjamsheer I'll remove them.

**Comment by SalShai** [comment]
@pjamsheer Could you check now??

**Comment by pjamsheer** [comment]
@SalShai one_fm/api/tasks.py in this file the notification messgae creation function can be optimised and reused for the two conditions

**Comment by SalShai** [comment]
okay. I'll check.

**Comment by pjamsheer** [comment]
@SalShai 
instead of `if status is None: or assigning status = None` use if status itself and status = False

**Comment by SalShai** [comment]
> @SalShai instead of `if status is None: or assigning status = None` use if status itself and status = False

@pjamsheer I tried this method before, but it did not work.

**Comment by pjamsheer** [comment]
@SalShai We can have a review meeting

**Comment by SalShai** [comment]
@pjamsheer Yes. sure.
When can I schedule it?

**Comment by SalShai** [comment]
@pjamsheer I have made the changes that was suggested by you. and have tested it as well. Kindly, Review it.

**Review by pjamsheer — APPROVED** [review]

**Pull request merged**
