### PR TITLE
[Feature] Optimize employee check in

### PR DESCRIPTION
**Pull request by NoBoneZ**
## Is this a Feature, Chore or Bug?
- [x] Feature
- [] Chore
- [] Bug

## Clearly and concisely describe the feature, chore or bug.
Employee check in instance takes a while to get created, due to the presence of redundant validation methods, which have been overriden, and also some queries in ONE-FM app were also optimized

## Analysis and design (optional)
Analyse and attach the design documentation

## Solution description
Describe your code changes in detail for reviewers.

## Is there a business logic within a doctype?
    - [] Yes
    - [x] No

## Output screenshots (optional)
Post the output screenshots, if a UI is affected or added due to this feature.

## Areas affected and ensured
List out the areas affected by your code changes.

## Is there any existing behavior change of other features due to this code change?
Mention Yes or No. If Yes, provide the appropriate explanation.

## Did you test with the following dataset?
- [] Existing Data
- [x] New Data

## Was child table created?
    - [] is attachment required?
        did you test attachment
## Did you delete custom field?
    - [] Yes
    - [x] No
        If yes, did you write a delete patch?

## Is patch required?
- [] Yes
- [x] No
    ## Was the patch test?

## Which browser(s) did you use for testing?
  - [x] Chrome
  - [] Safari
  - [] Firefox

Screenshot from 2022-12-26 08-00-22
Screenshot from 2022-12-26 07-54-20

Screenshot from 2022-12-27 22-57-43
Screenshot from 2022-12-27 22-46-44

### CODE REVIEW

**Review by SalShai — COMMENTED** [review]
Amazing Work!! LGTM!

**Comment by pjamsheer** [comment]
@mymi14s Shall we merge this?

**Comment by mymi14s** [comment]
@NoBoneZ @SalShai is this tested using the mobile app?

**Comment by NoBoneZ** [comment]
> @NoBoneZ @SalShai is this tested using the mobile app?

@mymi14s @pjamsheer @SalShai  i used postman to test it, i dont know if that would suffice, so i noticed that the microservice used takes about 10-11 seconds to scan and verify the person's face, and takes a total of 20 seconds before, i have been able to reduce it to 15 seconds
Screenshot from 2022-12-27 22-57-43
Screenshot from 2022-12-27 22-46-44

**Review by mymi14s — APPROVED** [review]

**Pull request merged**
