### PR TITLE
[HOT FIX] Update marital status field

### PR DESCRIPTION
**Pull request by NoBoneZ**
## Is this a Feature, Chore or Bug?
- [] Feature
- [] Chore
- [x] Bug

## Clearly and concisely describe the feature, chore or bug.
Update the options field in Employee with the new options provided by the government

## Analysis and design (optional)
Analyse and attach the design documentation

## Solution description
Describe your code changes in detail for reviewers.

## Is there a business logic within a doctype?
    - [] Yes
    - [x] No

## Output screenshots (optional)
Post the output screenshots, if a UI is affected or added due to this feature.

## Areas affected and ensured
List out the areas affected by your code changes.

## Is there any existing behavior change of other features due to this code change?
Mention Yes or No. If Yes, provide the appropriate explanation.

## Did you test with the following dataset?
- [x] Existing Data
- [] New Data

## Was child table created?
    - [] is attachment required?
        did you test attachment
## Did you delete custom field?
    - [] Yes
    - [x] No
        If yes, did you write a delete patch?

## Is patch required?
- [] Yes
- [] No
    ## Was the patch test?

## Which browser(s) did you use for testing?
  - [x] Chrome
  - [] Safari
  - [] Firefox

### CODE REVIEW

**Comment by pjamsheer** [comment]
@NoBoneZ Not able to find the change for Marital Status

**Comment by NoBoneZ** [comment]
> @NoBoneZ Not able to find the change for Marital Status

Please check it now, the changes are reflecting

**Comment by mymi14s** [comment]
@NoBoneZ correct wording Divorced not Divorce

**Comment by NoBoneZ** [comment]
> @NoBoneZ correct wording Divorced not Divorce

It was Divorce that was written on the government PAM file, that was sent to me

**Review by mymi14s — APPROVED** [review]

**Pull request merged**
